const getMealsMock = (userId) => {
  return [{
    name: 'Malvaceae',
    price: 972,
    userId,
    description: 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.',
    category: 'dolor sit',
  }, {
    name: 'Dryopteridaceae',
    price: 937,
    userId,
    description: 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    category: 'sed',
  }, {
    name: 'Saxifragaceae',
    price: 786,
    userId,
    description: 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.',
    category: 'placerat ante',
  }, {
    name: 'Brassicaceae',
    price: 914,
    userId,
    description: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    category: 'posuere cubilia',
  }, {
    name: 'Caprifoliaceae',
    price: 702,
    userId,
    description: 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.',
    category: 'volutpat quam',
  }, {
    name: 'Euphorbiaceae',
    price: 950,
    userId,
    description: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.',
    category: 'nulla',
  }, {
    name: 'Boraginaceae',
    price: 849,
    userId,
    description: 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
    category: 'nisl nunc',
  }, {
    name: 'Polypodiaceae',
    price: 763,
    userId,
    description: 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.',
    category: 'primis',
  }, {
    name: 'Gesneriaceae',
    price: 907,
    userId,
    description: 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.',
    category: 'diam',
  }, {
    name: 'Dicranaceae',
    price: 874,
    userId,
    description: 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.',
    category: 'sem sed',
  }, {
    name: 'Brachytheciaceae',
    price: 964,
    userId,
    description: 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.',
    category: 'non interdum',
  }, {
    name: 'Acanthaceae',
    price: 807,
    userId,
    description: 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
    category: 'sagittis',
  }, {
    name: 'Fabaceae',
    price: 755,
    userId,
    description: 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.',
    category: 'ac est',
  }, {
    name: 'Aristolochiaceae',
    price: 808,
    userId,
    description: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.',
    category: 'ut',
  }, {
    name: 'Myrtaceae',
    price: 836,
    userId,
    description: 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
    category: 'dis parturient',
  }, {
    name: 'Cyperaceae',
    price: 866,
    userId,
    description: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.',
    category: 'elit',
  }, {
    name: 'Solanaceae',
    price: 854,
    userId,
    description: 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.',
    category: 'ipsum',
  }, {
    name: 'Dryopteridaceae',
    price: 763,
    userId,
    description: 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.',
    category: 'vitae',
  }, {
    name: 'Teloschistaceae',
    price: 743,
    userId,
    description: 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.',
    category: 'morbi',
  }, {
    name: 'Asteraceae',
    price: 868,
    userId,
    description: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.',
    category: 'justo',
  }, {
    name: 'Goodeniaceae',
    price: 928,
    userId,
    description: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.',
    category: 'semper',
  }, {
    name: 'Valerianaceae',
    price: 857,
    userId,
    description: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.',
    category: 'phasellus',
  }, {
    name: 'Rosaceae',
    price: 876,
    userId,
    description: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    category: 'lectus',
  }, {
    name: 'Brassicaceae',
    price: 830,
    userId,
    description: 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
    category: 'consequat',
  }, {
    name: 'Scrophulariaceae',
    price: 852,
    userId,
    description: 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.',
    category: 'orci',
  }, {
    name: 'Liliaceae',
    price: 780,
    userId,
    description: 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.',
    category: 'urna ut',
  }, {
    name: 'Fagaceae',
    price: 768,
    userId,
    description: 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.',
    category: 'erat',
  }, {
    name: 'Papaveraceae',
    price: 916,
    userId,
    description: 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.',
    category: 'venenatis lacinia',
  }, {
    name: 'Boraginaceae',
    price: 776,
    userId,
    description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.',
    category: 'tortor quis',
  }, {
    name: 'Fabaceae',
    price: 804,
    userId,
    description: 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.',
    category: 'morbi',
  }, {
    name: 'Nyctaginaceae',
    price: 702,
    userId,
    description: 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.',
    category: 'nulla',
  }, {
    name: 'Scrophulariaceae',
    price: 947,
    userId,
    description: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.',
    category: 'eget',
  }, {
    name: 'Sphaerophoraceae',
    price: 939,
    userId,
    description: 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.',
    category: 'hendrerit at',
  }, {
    name: 'Malvaceae',
    price: 813,
    userId,
    description: 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.',
    category: 'leo',
  }, {
    name: 'Fagaceae',
    price: 752,
    userId,
    description: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.',
    category: 'amet nunc',
  }, {
    name: 'Asteraceae',
    price: 884,
    userId,
    description: 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',
    category: 'nisi',
  }, {
    name: 'Boraginaceae',
    price: 908,
    userId,
    description: 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
    category: 'auctor gravida',
  }, {
    name: 'Simaroubaceae',
    price: 935,
    userId,
    description: 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.',
    category: 'vestibulum sed',
  }, {
    name: 'Rubiaceae',
    price: 992,
    userId,
    description: 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.',
    category: 'luctus',
  }, {
    name: 'Fabaceae',
    price: 759,
    userId,
    description: 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.',
    category: 'in hac',
  }];
};

export default getMealsMock;
