let meals = [
  {
    id: 1,
    name: 'Chicken Pa-Naeng - Beef',
    description: 'Red Curry with Peanut Sauce, Bamboo Shoot, Ginger, Bell Pepper, Green Bean, Galanga and Lemon Leaves. Choice of Chicken, Beef, Pork, Tofu or Shrimp.',
    price: 2300,
    category: 'Hot Meal',
    image: '1.jpg',
  },
  {
    id: 2,
    name: 'Squash Curry - Tofu',
    description: 'Red and Yellow Curry Coconut Milk with Squash, Potatoes, Green Bean & Bamboo Shoot. Choice of Chicken, Beef, Pork, Tofu or Shrimp.',
    price: 1200,
    category: 'Lunch',
    image: '2.jpg',
  },
  {
    id: 3,
    name: 'Vegetable Fried Rice (Khao Phat Phak)',
    description: 'Stir Fried with Eggs, Chinese Broccoli, Tofu and Onion. Served with Cucumber and Lime.',
    price: 1500,
    category: 'Snack',
    image: '3.jpg',
  },
  {
    id: 4,
    name: 'Shrimp Frid Rice',
    description: 'Stir Fried Rice with Shrimp, Egg, Peas, Corn, Bean, Carrots, Onion. Topped with Cucumber and Lime.',
    price: 2000,
    category: 'Snack',
    image: '4.jpg',
  },
  {
    id: 5,
    name: 'Special Combination Fried Rice',
    description: 'Stir Fried Rice with Beef, Chicken, Pork, Shrimp, Chinese Sausage & Egg',
    price: 1400,
    category: 'Hot Meal',
    image: '5.jpg',
  },
  {
    id: 6,
    name: 'Yum - Pork',
    description: 'Slice Thin Beef Mixed With Lettuce, Thread Noodle, Lime, Onion, Carrot, Cilantro. Topped with Peanuts. Choice of Beef, Pork or Seafood.',
    price: 2100,
    category: 'Hot Meal',
    image: '6.jpg',
  },
  {
    id: 7,
    name: 'Yum - Seafood',
    description: 'Slice Thin Beef Mixed With Lettuce, Thread Noodle, Lime, Onion, Carrot, Cilantro. Topped with Peanuts. Choice of Beef, Pork or Seafood.',
    price: 1000,
    category: 'Lunch',
    image: '7.jpg',
  },
  {
    id: 8,
    name: 'Larb - Ground Beef',
    description: 'Ground Beef/Chicken/Pork mixed with Lemon Grass, Lemon Leaves, Onion, Cilantro, Green Onion, Basicl, and Ground Rice. Served with Cucumber and Cabbage/Lettuce.',
    price: 1300,
    category: 'Snack',
    image: '8.jpg',
  },
  {
    id: 9,
    name: 'Papaya Salad',
    description: 'Shredded Papaya, Lime, Pepper, Tomato, Dried Shrimp, Long Bean, Thai Eggplant, Fish Sauce, Peanuts. Served with Cabbage or Lettuce',
    price: 1000,
    category: 'Snack',
    image: '9.jpg',
  },
  {
    id: 10,
    name: 'Larb - Chicken',
    description: 'Ground Beef/Chicken/Pork mixed with Lemon Grass, Lemon Leaves, Onion, Cilantro, Green Onion, Basicl, and Ground Rice. Served with Cucumber and Cabbage/Lettuce.',
    price: 1200,
    category: 'Snack',
    image: '10.jpg',
  },
];


module.exports = meals;

